[package]
name = "aoc"
version = "0.1.0"
edition = "2021"
authors = ["Paul Sanders <paul@paulsanders.dev>"]
license = "MIT"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
rayon = "1.10.0"

[dev-dependencies]
tempfile = "3.14.0"
